def readfunc(spark):
    # df = spark.read.csv("file:///home/takeo/zipcodes.csv")
    # df.printSchema()
    # df.show(truncate=False)
    # df2= spark.read.option("header",True).csv("file:///home/takeo/zipcodes.csv")
    # df2.show()
    # print("before delimiter")
    df3 = spark.read.options(header='True', inferSchema='True', delimiter=',').csv("file:///home/takeo/zipcodes.csv")
    df3.printSchema()
    # df4 = spark.read.options(inferSchema='True', delimiter=',').csv("file:///home/takeo/zipcodes.csv")